services:
    db:
        image: mariadb:latest
        container_name: rolladex-db
        environment:
            MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
            MARIADB_DATABASE: ${DB_NAME}
            MARIADB_USER: ${DB_USERNAME}
            MARIADB_PASSWORD: ${DB_PASSWORD}
        volumes:
            - db_data:/var/lib/mysql
        healthcheck:
            test:
                [
                    "CMD-SHELL",
                    "mariadb-admin ping -h localhost -u root -p$$MARIADB_ROOT_PASSWORD",
                ]
            interval: 0m10s
            timeout: 1m0s
            retries: 5
            start_period: 10s

    backend:
        build:
            context: ./backend
            target: dist
        container_name: rolladex-api
        depends_on:
            db:
                condition: service_healthy

        env_file:
            - .env
        ports:
            - "3001:3001"
        environment:
            - DB_HOST=${DB_HOST}
            - DB_PORT=${DB_PORT}

    frontend:
        build:
            context: ./frontend
            target: base
        container_name: rolladex-ui

volumes:
    db_data:
